name: Label Sync

on:
  label:
    types: [created, edited, deleted]
  push:
    branches:
      - master

jobs:
  label-sync:
    name: Label Sync
    runs-on: ubuntu-latest
    env:
      GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      LABEL_REPO_SOURCE: patcon/archive-demo
      LABEL_REPO_TARGET: patcon/labeler-demo
    steps:
      - uses: MilesChou/composer-action@master
        with:
          args: global require vanilla/github-sync
      - run: github-sync labels --from $LABEL_REPO_SOURCE --to $LABEL_REPO_TARGET --delete prune

