name: Label Sync

on:
  label:
    types: [created, edited, deleted]
  push:
    branches:
      - master

jobs:
  label-sync:
    name: Label Sync
    runs-on: ubuntu-latest
    env:
      GITHUB_API_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
      LABEL_REPO_SOURCE: patcon/archive-demo
      LABEL_REPO_TARGETS: patcon/labeler-demo patcon/labeller-demo-2
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: '7.3'
          extension-csv: mbstring, xdebug #optional, setup extensions
          ini-values-csv: post_max_size=256M, short_open_tag=On #optional, setup php.ini configuration
          coverage: xdebug #optional, setup coverage driver
          pecl: true #optional, setup PECL
      - run: |
          composer require vanilla/github-sync
          for target in $LABEL_REPO_TARGETS; do
            ./vendor/bin/github-sync labels --from $LABEL_REPO_SOURCE --to target --delete prune
          end
